ThingStoreProject/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ThingStoreProject.views.home', name='home'),
    # url(r'^ThingStoreProject/', include('ThingStoreProject.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('thingstore.urls')),
)

thingstore/urls.py
from django.conf.urls import patterns, url,include
from django.http import HttpResponseRedirect

from thingstore import views,api

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    # url(r'^login/$', views.login_view, name='login'),
    # url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^thing/(?P<thing_id>\d+)/$', views.thing, name='thing'),
    url(r'^thing/(?P<thing_id>\d+)/edit/$', views.thing_editor, name='thing_editor'),
    url(r'^thing/new/$', views.thing_editor, name='thing_new'),
    url(r'^user/(?P<username>\w+)/$', views.user, name='user'),
    
    url(r'^settings/$', lambda x: HttpResponseRedirect('/settings/apikeys')),
    url(r'^settings/personal/$', views.settings_personal, name='settings_personal'),
    url(r'^settings/apikeys/$', views.settings_apikeys, name='settings_apikeys'),
    url(r'^settings/apikeys/add/$', views.settings_apikeys_add, name='settings_apikeys_add'),
    url(r'^settings/apikeys/del/(?P<apikey_id>\d+)/$', views.settings_apikeys_del, name='settings_apikeys_del'),
    
    
    url(r'^api/', include(api.urls)),
)

ThingStoreProject/thingstore/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils.timezone import now, utc
import calendar, datetime


# Create your models here.

class Thing(models.Model):
	name = models.CharField(max_length=255)
	location = models.CharField(max_length=255, blank=True)
	description = models.TextField(blank=True)
	owner = models.ForeignKey(User)
	
	def __unicode__(self):
		return self.name;

class Metric(models.Model):
	thing = models.ForeignKey(Thing, related_name='metrics')
	name = models.CharField(max_length=255)
	unit = models.CharField(max_length=64, blank=True)
	
	class Meta:
		unique_together = (("name","thing"),)
	
	def __unicode__(self):
		return self.name;
	
	""" Return most recent value for metric """
	@property
	def current_value(self):
		try:
			return Value.objects.filter(metric = self)[:1].get().value
		except Value.DoesNotExist:
			return None
	
	""" set current value by adding a new Value with current timestamp"""
	@current_value.setter
	def current_value(self, value):
		v = Value(metric = self, value = value)
		v.save()
	
	""" Return datetime of last update """
	@property
	def last_update(self):
		try:
			return Value.objects.filter(metric = self)[:1].get().timestamp
		except Value.DoesNotExist:
			return None

	def getValues(self, timeframe_hours):
		try:
			return Value.objects.filter(metric = self, timestamp__gte = now()-datetime.timedelta(hours=timeframe_hours)).order_by('timestamp')
		except:
			return None;


class Value(models.Model):
	metric = models.ForeignKey(Metric, related_name='values')
	value = models.FloatField()
	timestamp = models.DateTimeField(default=now)
	
	@property
	def js_time(self):
		return calendar.timegm(self.timestamp.timetuple())*1000
	
	class Meta:
		ordering = ['-timestamp']
	
class APIKey(models.Model):
	token = models.CharField(max_length=255, unique = True)
	user = models.ForeignKey(User, related_name='apikeys')
	

thingstore/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils.timezone import now, utc
import calendar, datetime, string, random

# Create your models here.

class Thing(models.Model):
	name = models.CharField(max_length=255)
	location = models.CharField(max_length=255, blank=True)
	description = models.TextField(blank=True)
	owner = models.ForeignKey(User)
	
	def __unicode__(self):
		return self.name;
		
	def get_absolute_url(self):
		return reverse('thingstore.views.thing', args=[str(self.id)])

class Metric(models.Model):
	thing = models.ForeignKey(Thing, related_name='metrics')
	name = models.CharField(max_length=255)
	unit = models.CharField(max_length=64, blank=True)
	no_interpolation = models.BooleanField(default=False)
	
	class Meta:
		unique_together = (("name","thing"),)
	
	def __unicode__(self):
		return self.name;
	
	""" Return most recent value for metric """
	@property
	def current_value(self):
		try:
			return Value.objects.filter(metric = self)[:1].get().value
		except Value.DoesNotExist:
			return None
	
	""" set current value by adding a new Value with current timestamp"""
	@current_value.setter
	def current_value(self, value):
		v = Value(metric = self, value = value)
		v.save()
	
	""" Return datetime of last update """
	@property
	def last_update(self):
		try:
			return Value.objects.filter(metric = self)[:1].get().timestamp
		except Value.DoesNotExist:
			return None

	""" Returns a list of Value objects for the last $timeframe_hours
		plus the one Value before the timeframe if existing """
	def getValues(self, timeframe_hours):
		try:
			# Get all values within the timeframe
			r_values = Value.objects.filter(metric = self, timestamp__gte = now()-datetime.timedelta(hours=timeframe_hours)).order_by('timestamp')
			r_list = [ values for values in r_values]
			
			# The invisible Value outside of the Timeframe
			inv_value = Value.objects.filter(metric = self, timestamp__lt = now()-datetime.timedelta(hours=timeframe_hours)).order_by('-timestamp')[:1]
			
			if inv_value.count():
				vr_list = list(inv_value) + list(r_values)
				return vr_list
			return r_list
		except:
			return None;


class Value(models.Model):
	metric = models.ForeignKey(Metric, related_name='values')
	value = models.FloatField()
	timestamp = models.DateTimeField(default=now)
	
	@property
	def js_time(self):
		return calendar.timegm(self.timestamp.timetuple())*1000
	
	class Meta:
		ordering = ['-timestamp']
	
class APIKey(models.Model):
	token = models.CharField(max_length=255, unique = True)
	user = models.ForeignKey(User, related_name='apikeys')

	@classmethod
	def create(cls, user):
		apikey = cls(user=user)
		apikey.token = ''.join(random.sample(string.lowercase+string.uppercase+string.digits,32))
		return apikey

thingstore/forms.py
from django.forms import ModelForm
from thingstore.models import Thing

class ThingForm(ModelForm):
	class Meta:
		model = Thing
		exclude = ['owner']

thingstore/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, render_to_response
from django.utils.timezone import now
from datetime import timedelta
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.forms.models import inlineformset_factory
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import validate_email

from thingstore.models import Thing, Value, APIKey, Metric
from thingstore.forms import ThingForm


""" Index page. Contains lists of users and things """
def index(request):
	latest_things = Thing.objects.order_by('name')[:5]
	users = User.objects.order_by('-last_login')[:5]
	context = {'latest_things': latest_things, 'users': users}
	return render(request, 'thingstore/index.html', context)

""" About page. Static """
def about(request):
	context = {}
	return render(request, 'thingstore/about.html', context)

""" Thing detail page """
def thing(request, thing_id):
	timeframe_hours = 12
	
	# Create Querysets
	thing = get_object_or_404(Thing, pk=thing_id)
	metrics = thing.metrics.all()
	values = Value.objects.filter(metric__in = metrics, timestamp__gte = now()-timedelta(hours=timeframe_hours))
	
	# Put values as dict in a bigger dict
	relation_dict = {}
	for value in values:
		value_dict = value.__dict__
		value_dict['js_time'] = value.js_time
		relation_dict.setdefault(value.metric_id, []).append(value_dict)
	
	# Create dict of metrics, add values from ^ dict
	metrics_list = []
	for metric in metrics:
		metric_dict = metric.__dict__
		metric_dict['current_value'] = metric.current_value
		if metric.id in relation_dict:
			metric_dict['value_dict'] = relation_dict[metric.id]
			
			# add latest invisible value to have a line out of nowhere into the left side of the graph
			invisible_value = Value.objects.filter(metric = metric, timestamp__lt = now()-timedelta(hours=timeframe_hours))[:1]
			if len(invisible_value) == 1:
				value_dict = invisible_value[0].__dict__
				value_dict['js_time'] = invisible_value[0].js_time
				metric_dict['value_dict'].append(value_dict)
		
		metrics_list.append(metric_dict)

	return render(request, 'thingstore/thing.html',
		{
			'thing': thing,
			'metrics': metrics_list,
			'timeframe_hours': timeframe_hours
		}
	)	

""" User detail page """
def user(request, username):
	user = get_object_or_404(User, username__iexact=username)
	return render(request, 'thingstore/user.html', {'selected_user': user})
	
def login_view(request):
	#state = "Please log in below..."
	username = password = ''
	parameters = {}
	parameters.update(csrf(request))
	
	if request.POST:
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('thingstore.views.index'))
			else:
				parameters['alert'] = "Your account is not active, please contact the site admin."
		else:
			parameters['alert'] = "Your username and/or password were incorrect."
	

	parameters['username'] = username
	
	return render_to_response('thingstore/login.html',parameters)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('thingstore.views.index'))

@login_required
def settings_personal(request):
	parameters = {}
	if request.POST:
		action = request.POST.get('action')
		user = request.user
		
		if action == "change_password":
			curr_password = request.POST.get('curr_password')
			password = request.POST.get('new_password')
			password_retype = request.POST.get('new_password_retype')
			
			if not user.check_password(curr_password):
				parameters["error"] = "Please enter your correct current password"
			elif password <> password_retype:
				parameters["error"] = "Please type the same password twice."
			elif len(password) < settings.PASSWORD_MIN_LENGTH:
				parameters["error"] = "Your password has to be at least " + str(settings.PASSWORD_MIN_LENGTH) + " characters long."
			else:
				#TODO: Password requirements
				user.set_password(password)
				user.save()
				parameters["message"] = "Password successfully changed."
		elif action == "change_email":
			curr_password = request.POST.get('curr_password')
			email = request.POST.get('email')
			
			if not user.check_password(curr_password):
				parameters["error"] = "Please enter your correct current password"
			else:
				try:
					validate_email(email)
				except ValidationError as e:
					parameters["error"] =  "Please enter a valid email address"
				else:
					user.email = email
					user.save()
					parameters["message"] = "Email address successfully changed."
		
	parameters["tab"] = "personal"
	return render(request, 'thingstore/settings_personal.html', parameters)	

@login_required
def settings_apikeys(request):
	parameters = {}
	parameters["tab"] = "apikeys"
	parameters["apikeys"] = request.user.apikeys.all()
	return render(request, 'thingstore/settings_apikeys.html', parameters)

@login_required
def settings_apikeys_add(request):
		apikey = APIKey.create(request.user)
		apikey.save()
		return HttpResponseRedirect(reverse('thingstore.views.settings_apikeys'))

@login_required
def settings_apikeys_del(request, apikey_id):
		apikey = APIKey.objects.get(pk=apikey_id)
		if apikey.user != request.user:
			# TODO: Error message
			return HttpResponseRedirect(reverse('thingstore.views.settings_apikeys'))
		apikey.delete()
		#TODO: Success message
		return HttpResponseRedirect(reverse('thingstore.views.settings_apikeys'))

""" Thing editor """
# TODO: Error handling
@login_required
def thing_editor(request, thing_id = None):
	# TODO: Move to forms.py
	MetricFormSet = inlineformset_factory(Thing, Metric)
	
	thing = None
	
	if request.method == "POST":
		if thing_id:
			thing = get_object_or_404(Thing, pk=thing_id)
			if thing.owner <> request.user:
				# TODO: Error Message
				return HttpResponseRedirect(thing.get_absolute_url())
			thing_form = ThingForm(request.POST, instance=thing)
		else:
			thing_form = ThingForm(request.POST)
		if thing_form.is_valid():
			thing_from_form = thing_form.save(commit = False)
			thing_from_form.owner = request.user
			formset = MetricFormSet(request.POST, instance=thing_from_form)
			if formset.is_valid():
				thing_from_form.save()
				formset.save()
				return HttpResponseRedirect(thing_from_form.get_absolute_url())
	else:
		if thing_id:
			thing = get_object_or_404(Thing, pk=thing_id)
			if thing.owner <> request.user:
				# TODO: Error Message
				return HttpResponseRedirect(thing.get_absolute_url())
			thing_form = ThingForm(instance=thing)
			formset = MetricFormSet(instance=thing)
		else:
			thing_form = ThingForm()
			formset = MetricFormSet()

	return render(request, 'thingstore/thing_edit.html',
		{
			'thing': thing,
			'thing_form': thing_form,
			'metric_formset': formset
		}
	)	

thingstore/templates/thingstore/about.html
{% extends "thingstore/base.html" %}

{% block content %}
<div class="row">
	<div class="col-sm-8">
		<h2>About ThingStore</h2>
		<p>ThingStore is an open source project, allowing you to store and visualize numerical data from all kinds of sources. Connect sensors, monitor your computers, or track your finances. Using its open API, you can push data to ThingStore, visualize it in pretty graphs, and later extract it again, to do other fun stuff with it. Eventually, you will be able to set triggers directly from within ThingStore, and use them to execute certain actions whenever your data changes in a defined way. But we're not quite that yet.</p>
		
		<h3>Structure</h3>
		<p>In ThingStore, data is grouped by Things. Each thing can have multiple metrics, which define one timeseries of numerical data points. A thing always belongs to a single user. Additionally, each user can define multiple API keys, to access the ThingStore API without having to provide username and password. For now, all API keys are created equal, but eventually, users will be able to set different permissions for different API keys.</p>
	</div>
	<div class="col-sm-4">
		<h2>Open Source</h2>
		<p>ThingStore is released under the MIT open source license. Feel free to <a href="https://github.com/tiefpunkt/thingstore">contribute</a>, and make ThingStore more awesome.</p>
		<p>If your find a bug or are missing a feature, feel free to fork our <a href="https://github.com/tiefpunkt/thingstore">GitHub Repository</a>, or leave us a note in form of an <a href="https://github.com/tiefpunkt/thingstore/issues/new">issue</a>.</p>
	</div>
</div>
{% endblock %}

thingstore/templates/thingstore/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">

		<title>{% block title %}ThingStore{% endblock %}</title>

		{% load staticfiles %}

		<link rel="shortcut icon" href="{% static 'thingstore/favicon.ico' %}">

		<!-- Bootstrap core CSS -->
		<link href="{% static 'thingstore/css/bootstrap.min.css' %}" rel="stylesheet">

		<!-- Custom styles for this template -->
		<link href="{% static 'thingstore/css/jumbotron.css' %}" rel="stylesheet">
		<link href="{% static 'thingstore/css/thingstore.css' %}" rel="stylesheet">
		
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="../../assets/js/html5shiv.js"></script>
			<script src="../../assets/js/respond.min.js"></script>
		<![endif]-->
	</head>

	<body>

		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/">ThingStore</a>
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li class="active"><a href="/">Home</a></li>
						<li><a href="/about">About</a></li>
						<li><a href="#contact">Contact</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">More <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="/impressum">Impressum</a></li>
								{% if user.is_staff %}
									<li class="divider"></li>
									<li class="dropdown-header">Management</li>
									<li><a href="/admin">Administration</a></li>
								{% endif %}
							</ul>
						</li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						{% if user.is_authenticated %}
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as {{ user.username }} <b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li><a href="/thing/new/">New Thing</a></li>
									<li class="divider"></li>
									<li><a href="/user/{{ user.username }}/">Profile</a></li>
									<li><a href="/settings/">Settings</a></li>
									<li class="divider"></li>
									<li><a href="/accounts/logout/">Logout</a></li>
								</ul>
						{% else %}
							<li><a href="/accounts/login/">Login</a></li>
							<li><a href="/accounts/register/">Sign Up</a></li>
						{% endif %}
					  </ul>
				</div><!--/.navbar-collapse -->
			</div>
		</div>

		{% block header %}{% endblock %}

		<div class="container">
			{% block content %}{% endblock %}

			<hr>

			<footer>
				<p>Powered by <a href="https://github.com/tiefpunkt/thingstore">ThingStore</a>. Help us make this more awesome by contributing.</p>
			</footer>
		</div> <!-- /container -->


		<!-- Bootstrap core JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="{% static 'thingstore/js/jquery.min.js' %}"></script>
		<script src="{% static 'thingstore/js/bootstrap.min.js' %}"></script>
		{% block javascript %}{% endblock %}
	</body>
</html>

thingstore/templates/thingstore/index.html
{% extends "thingstore/base.html" %}

{% block content %}
<div class="row">
	<div class="col-sm-4">
		<h2>Users</h2>
		{% if users %}
			<ul>
				{% for user in users %}
					<li><a href="{% url 'user' user.username %}">{{ user }}</a></li>
				{% endfor %}
			</ul>
		{% else %}
			<p>No users are available.</p>
		{% endif %}
	</div>
	<div class="col-sm-4">
		<h2>Things</h2>
		{% if latest_things %}
			<ul>
				{% for thing in latest_things %}
					<li><a href="{% url 'thing' thing.id %}">{{ thing.name }}</a></li>
				{% endfor %}
			</ul>
		{% else %}
			<p>No things are available.</p>
		{% endif %}
	</div>
	<div class="col-sm-4">
		<h2>About ThingStore</h2>
		<p>ThingStore is an open source project, allowing you to store and visualize numerical data from all kinds of sources. Connect sensors, monitor your computers, or track your finances.</p>
		<p><a class="btn btn-default" href="/about">View details &raquo;</a></p>
	</div>
</div>
{% endblock %}

{% block header %}
<div class="jumbotron">
	<div class="container">
		<h1>ThingStore</h1>
		<p>The thing where things go to store their stuff.</p>
		<p><a class="btn btn-primary btn-lg" href="/about">Learn more &raquo;</a></p>
	</div>
</div>
{% endblock %}

thingstore/templates/thingstore/login.html
{% extends "thingstore/base.html" %}

{% block content %}
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h2>Login</h2>
			
			{% if alert %}
				<div class="alert alert-danger alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					{{ alert }}
				</div>
			{% endif %}
	
			<form method="POST" action="" accept-charset="UTF-8" class="form-horizontal" role="form">
				{% csrf_token %} 
				{% if next %}
					<input type="hidden" name="next" value="{{ next }}" />
				{% endif %}
			
				<div class="form-group">
					<label for="username" class="col-sm-3 control-label">Username</label>
					<div class="col-sm-9">
						<input type="text" class="form-control" id="username" name="username" placeholder="Username">
					</div>
				</div>
			
				<div class="form-group">
					<label for="password" class="col-sm-3 control-label">Password</label>
					<div class="col-sm-9">
						<input type="password" class="form-control" id="password" name="password" placeholder="Password">
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-3 col-sm-9">
						<button type="submit" class="btn btn-primary">Sign in</button>
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

thingstore/templates/thingstore/settings.html
{% extends "thingstore/base.html" %}

{% block content %}
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			<h2>Settings</h2>
			
			{% if error %}
					<div class="alert alert-danger alert-dismissable">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						{{ error }}
					</div>
				{% endif %}
				{% if message %}
					<div class="alert alert-success alert-dismissable">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						{{ message }}
					</div>
				{% endif %}
				
					<ul class="nav nav-tabs">
						<li {% if tab == "personal" %}class="active" {% endif %}><a href="/settings/personal/">Personal data</a></li>
						<li {% if tab == "apikeys" %}class="active" {% endif %}><a href="/settings/apikeys/">API keys</a></li>
					</ul>
					
			<!-- Tab panes -->
			<div class="tab-content">
				
				{% block tab_content %}{% endblock %}
			</div>
		</div>
	</div>
{% endblock %}

thingstore/templates/thingstore/settings_apikeys.html
{% extends "thingstore/settings.html" %}

{% block tab_content %}
	<h3>My API keys</h3>
	<a href="add/">Add new API Key</a>
	<ul class="list-group">
		{% for apikey in apikeys %}
			<li class="list-group-item">{{apikey.token}}<a href="del/{{apikey.id}}/" type="button" class="close" aria-hidden="true" >&times;</a></li>
		{% endfor %}
	</ul>
{% endblock %}

thingstore/templates/thingstore/settings_personal.html
{% extends "thingstore/settings.html" %}

{% block tab_content %}
	<h3>My personal data</h3>
	
	<h4>Password</h4>
	<form method="POST" action="" accept-charset="UTF-8" class="form-horizontal" role="form">
		{% csrf_token %} 
		{% if next %}
			<input type="hidden" name="next" value="{{ next }}" />
		{% endif %}
		<input type="hidden" name="action" value="change_email" />
		
		<div class="form-group">
			<label for="email" class="col-sm-3 control-label">Email Address</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" id="email" name="email" placeholder="Email address">
			</div>
		</div>
		
		<div class="form-group">
			<label for="curr_password" class="col-sm-3 control-label">Current password</label>
			<div class="col-sm-9">
				<input type="password" class="form-control" id="curr_password" name="curr_password" placeholder="Current password">
			</div>
		</div>
		
		<div class="form-group">
			<div class="col-sm-offset-3 col-sm-9">
				<button type="submit" class="btn btn-primary">Change Email Address</button>
			</div>
		</div>
  </form>
	
	<h4>Password</h4>
	<form method="POST" action="" accept-charset="UTF-8" class="form-horizontal" role="form">
		{% csrf_token %} 
		{% if next %}
			<input type="hidden" name="next" value="{{ next }}" />
		{% endif %}
		<input type="hidden" name="action" value="change_password" />		
		<div class="form-group">
			<label for="curr_password" class="col-sm-3 control-label">Current password</label>
			<div class="col-sm-9">
				<input type="password" class="form-control" id="curr_password" name="curr_password" placeholder="Current password">
			</div>
		</div>
		
		<div class="form-group">
			<label for="new_password" class="col-sm-3 control-label">New password</label>
			<div class="col-sm-9">
				<input type="password" class="form-control" id="new_password" name="new_password" placeholder="New password">
			</div>
		</div>
		
		<div class="form-group">
			<label for="new_password_retype" class="col-sm-3 control-label">Retype new password</label>
			<div class="col-sm-9">
				<input type="password" class="form-control" id="new_password_retype" name="new_password_retype" placeholder="Retype new password">
			</div>
		</div>
		
		<div class="form-group">
			<div class="col-sm-offset-3 col-sm-9">
				<button type="submit" class="btn btn-primary">Change Password</button>
			</div>
		</div>
  </form>
{% endblock %}

thingstore/templates/thingstore/thing_edit.html
{% extends "thingstore/base.html" %}
{% load form_extras %}

{% block content %}
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<h2>
			{% if thing %}
			  Edit Thing - {{ thing.name }}
			{% else %}
				New Thing
			{% endif %}
		</h2>
		<form method="POST" class="form-horizontal" role="form">
			{% csrf_token %}
			{% for field in thing_form.visible_fields %}
				<div class="form-group">
					<label for="{{ field.id_for_label }}" class="col-sm-4 control-label">{{ field.label }}</label>
					<div class="col-sm-8">
						{% if field.field.widget|fieldtype == "Textarea" %}
							<textarea class="form-control" id="{{ field.id_for_label }}" name="{{ field.html_name }}" placeholder="{{ field.label }}">{{ field.value|default_if_none:"" }}</textarea>
						{% else %}
							<input type="text" class="form-control" id="{{ field.id_for_label }}" name="{{ field.html_name }}" placeholder="{{ field.label }}" value="{{ field.value|default_if_none:"" }}">
						{% endif %}
					</div>
					
					{% if field.errors %}
						<div class="alert alert-danger alert-dismissable">
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							{{ field.errors|join:", " }}
						</div>
					{% endif %}
				</div>
			{% endfor %}
		<h3>Metrics</h3>
		
   
		{{metric_formset.management_form}}
    {% for form in metric_formset %}
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="form-inline" role="form">
						{% for field in form.hidden_fields %}
							{{ field }}
						{% endfor %}
						{% for field in form.visible_fields %}
							<div class="form-group col-sm-4">
								{% if field.field.widget|fieldtype == "CheckboxInput" %}
									<label class="checkbox-inline">
										{{ field }}
										{{ field.label }}
									</label>
								{% else %}
									<label class="sr-only" for="{{ field.id_for_label }}">{{ field.label }}</label>
									<input type="text" class="form-control" id="{{ field.id_for_label }}" name="{{ field.html_name }}" placeholder="{{ field.label }}" value="{{ field.value|default_if_none:"" }}">
								{% endif %}
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
		{% endfor %}
			<div class="form-group">
					<button type="submit" class="btn btn-primary">Save</button>
			</div>
		</form>
	</div>
</div>
{% endblock %}

thingstore/templates/thingstore/user.html
{% extends "thingstore/base.html" %}

{% block content %}
<div class="row">
	<div class="col-sm-8">
		<h1>{{ selected_user }}</h1>
		<ul>
		{% for thing in selected_user.thing_set.all %}
			<li><a href="{% url 'thing' thing.id %}">{{ thing.name }}</a></li>
		{% endfor %}
		</ul>
	</div>
</div>
{% endblock %}